// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailwayReservation.Infrastructure.Persistence;

#nullable disable

namespace RailwayReservation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804061510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("booking_reference");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationStationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("destination_station_id");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("journey_id");

                    b.Property<Guid>("OriginStationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("origin_station_id");

                    b.Property<string>("PassengerContact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("passenger_contact");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("passenger_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalFare")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_fare");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("BookingReference")
                        .IsUnique()
                        .HasDatabaseName("ux_bookings_booking_reference");

                    b.HasIndex("DestinationStationId")
                        .HasDatabaseName("ix_bookings_destination_station_id");

                    b.HasIndex("JourneyId")
                        .HasDatabaseName("ix_bookings_journey_id");

                    b.HasIndex("OriginStationId")
                        .HasDatabaseName("ix_bookings_origin_station_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.BookingSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("char(36)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DestinationOrder")
                        .HasColumnType("int")
                        .HasColumnName("destination_order");

                    b.Property<decimal>("Fare")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fare");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("journey_id");

                    b.Property<int>("OriginOrder")
                        .HasColumnType("int")
                        .HasColumnName("origin_order");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("char(36)")
                        .HasColumnName("seat_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_booking_segments");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_segments_booking_id");

                    b.HasIndex("JourneyId")
                        .HasDatabaseName("ix_booking_segments_journey_id");

                    b.HasIndex("SeatId", "JourneyId")
                        .HasDatabaseName("ix_booking_segments_seat_id_journey_id");

                    b.ToTable("booking_segments", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.BookingSegmentLeg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BookingSegmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("booking_segment_id");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("journey_id");

                    b.Property<int>("LegOrder")
                        .HasColumnType("int")
                        .HasColumnName("leg_order");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("char(36)")
                        .HasColumnName("seat_id");

                    b.HasKey("Id")
                        .HasName("pk_booking_segment_legs");

                    b.HasIndex("BookingSegmentId")
                        .HasDatabaseName("ix_booking_segment_legs_booking_segment_id");

                    b.HasIndex("SeatId", "JourneyId", "LegOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_segment_legs_seat_journey_leg");

                    b.ToTable("booking_segment_legs", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CoachNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("coach_number");

                    b.Property<string>("CoachType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("coach_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("char(36)")
                        .HasColumnName("train_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_coaches");

                    b.HasIndex("TrainId")
                        .HasDatabaseName("ix_coaches_train_id");

                    b.HasIndex("TrainId", "CoachNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_coaches_train_id_coach_number");

                    b.ToTable("coaches", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.FareRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CoachType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("coach_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("rule_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_fare_rules");

                    b.HasIndex("RuleType", "IsActive")
                        .HasDatabaseName("ix_fare_rules_rule_type_is_active");

                    b.ToTable("fare_rules", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Journey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("departure_time");

                    b.Property<DateOnly>("JourneyDate")
                        .HasColumnType("date")
                        .HasColumnName("journey_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("char(36)")
                        .HasColumnName("train_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_journeys");

                    b.HasIndex("JourneyDate")
                        .HasDatabaseName("ix_journeys_journey_date");

                    b.HasIndex("TrainId", "JourneyDate")
                        .IsUnique()
                        .HasDatabaseName("ix_journeys_train_id_journey_date");

                    b.ToTable("journeys", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("char(36)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("transaction_ref");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_payments_booking_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("char(36)")
                        .HasColumnName("coach_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("seat_number");

                    b.Property<string>("SeatType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("seat_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("CoachId")
                        .HasDatabaseName("ix_seats_coach_id");

                    b.HasIndex("CoachId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_seats_coach_id_seat_number");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("distance_km");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_stations_code");

                    b.HasIndex("Order")
                        .IsUnique()
                        .HasDatabaseName("ix_stations_order");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Train", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsExpress")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_express");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trains");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_trains_code");

                    b.ToTable("trains", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.WaitlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationStationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("destination_station_id");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("journey_id");

                    b.Property<Guid>("OriginStationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("origin_station_id");

                    b.Property<string>("PassengerContact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("passenger_contact");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("passenger_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_waitlist_entries");

                    b.HasIndex("DestinationStationId")
                        .HasDatabaseName("ix_waitlist_entries_destination_station_id");

                    b.HasIndex("OriginStationId")
                        .HasDatabaseName("ix_waitlist_entries_origin_station_id");

                    b.HasIndex("JourneyId", "Status")
                        .HasDatabaseName("ix_waitlist_entries_journey_id_status");

                    b.ToTable("waitlist_entries", (string)null);
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Booking", b =>
                {
                    b.HasOne("RailwayReservation.Domain.Entities.Station", "DestinationStation")
                        .WithMany()
                        .HasForeignKey("DestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_stations_destination_station_id");

                    b.HasOne("RailwayReservation.Domain.Entities.Journey", "Journey")
                        .WithMany("Bookings")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_journeys_journey_id");

                    b.HasOne("RailwayReservation.Domain.Entities.Station", "OriginStation")
                        .WithMany()
                        .HasForeignKey("OriginStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_stations_origin_station_id");

                    b.Navigation("DestinationStation");

                    b.Navigation("Journey");

                    b.Navigation("OriginStation");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.BookingSegment", b =>
                {
                    b.HasOne("RailwayReservation.Domain.Entities.Booking", "Booking")
                        .WithMany("Segments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_segments_bookings_booking_id");

                    b.HasOne("RailwayReservation.Domain.Entities.Journey", "Journey")
                        .WithMany("BookingSegments")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_segments_journeys_journey_id");

                    b.HasOne("RailwayReservation.Domain.Entities.Seat", "Seat")
                        .WithMany("BookingSegments")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_segments_seats_seat_id");

                    b.Navigation("Booking");

                    b.Navigation("Journey");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.BookingSegmentLeg", b =>
                {
                    b.HasOne("RailwayReservation.Domain.Entities.BookingSegment", "BookingSegment")
                        .WithMany("Legs")
                        .HasForeignKey("BookingSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_segment_legs_booking_segments_booking_segment_id");

                    b.Navigation("BookingSegment");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Coach", b =>
                {
                    b.HasOne("RailwayReservation.Domain.Entities.Train", "Train")
                        .WithMany("Coaches")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coaches_trains_train_id");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Journey", b =>
                {
                    b.HasOne("RailwayReservation.Domain.Entities.Train", "Train")
                        .WithMany("Journeys")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journeys_trains_train_id");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Payment", b =>
                {
                    b.HasOne("RailwayReservation.Domain.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Seat", b =>
                {
                    b.HasOne("RailwayReservation.Domain.Entities.Coach", "Coach")
                        .WithMany("Seats")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seats_coaches_coach_id");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.WaitlistEntry", b =>
                {
                    b.HasOne("RailwayReservation.Domain.Entities.Station", "DestinationStation")
                        .WithMany()
                        .HasForeignKey("DestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_waitlist_entries_stations_destination_station_id");

                    b.HasOne("RailwayReservation.Domain.Entities.Journey", "Journey")
                        .WithMany("WaitlistEntries")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_waitlist_entries_journeys_journey_id");

                    b.HasOne("RailwayReservation.Domain.Entities.Station", "OriginStation")
                        .WithMany()
                        .HasForeignKey("OriginStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_waitlist_entries_stations_origin_station_id");

                    b.Navigation("DestinationStation");

                    b.Navigation("Journey");

                    b.Navigation("OriginStation");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.BookingSegment", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Coach", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Journey", b =>
                {
                    b.Navigation("BookingSegments");

                    b.Navigation("Bookings");

                    b.Navigation("WaitlistEntries");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Seat", b =>
                {
                    b.Navigation("BookingSegments");
                });

            modelBuilder.Entity("RailwayReservation.Domain.Entities.Train", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Journeys");
                });
#pragma warning restore 612, 618
        }
    }
}
